model:
  type: "openai"  # "openai" or "local"
  name: "gpt-4o"
  temperature: 0.0
  openai_api_key: "sk-your-openai-api-key"
  openai_base_url: "https://api.openai.com/v1"

# 如果使用本地模型，配置如下:
# model:
#   type: "openai"
#   name: "gpt-4o"
#   temperature: 0.0
#   openai_api_key: "sk-your-openai-api-key"
#   openai_base_url: "https://api.openai.com/v1"
