model:
  type: "openai"  # "openai" or "local"
  name: "gpt-4o"
  temperature: 0.0
  openai_api_key: "sk-lNAfLdE1AMKr6AV6a3qaNZ86BIPdEUKdyZ26VogskVpeCDjn"
  openai_base_url: "http://47.254.87.71:3000/v1"

# 如果使用本地模型，配置如下:
# model:
#   type: "local"
#   name: "Qwen2.5-VL-72B-Instruct"
#   temperature: 0.0
#   port: 8000
