# S2 Meta Protocol Configuration for Safety_Tech
# Intelligent protocol routing for S2 security testing

general:
  # S2 testing focus - determines protocol routing strategy
  test_focus: "comprehensive"  # comprehensive, tls_focused, e2e_focused, session_focused
  
  # Protocol routing settings
  enable_cross_protocol: true  # Enable cross-protocol communication testing
  enable_llm_routing: true     # Use LLM for intelligent protocol selection
  
  # Testing parameters  
  num_conversations: 3         # Number of medical case conversations
  max_rounds: 2               # Conversation rounds per case (reduced for security focus)
  
  # S2 security testing options
  enable_mitm: false          # Enable MITM testing (requires elevated privileges)
  enable_comprehensive_probes: true  # Enable all S2 security probes
  
  # Protocol selection (fallback when LLM unavailable)
  fallback_protocol: "anp"  # Highest S2 scoring protocol

# Core LLM configuration for intelligent routing
core:
  type: "openai"  # Uses OpenAI-compatible client for NVIDIA
  name: "gpt-4o"  # NVIDIA LLaMA model
  temperature: 0.1  # Lower temperature for security decisions
  openai_api_key: "sk-your-openai-api-key"
  openai_base_url: "https://api.openai.com/v1"

# S2 Comprehensive Security Probes Configuration
s2_probes:
  # TLS/Transport Layer Security (Weight: 40%)
  tls_downgrade:
    enabled: true
    weak_versions: ["TLSv1.0", "TLSv1.1"]
    weak_ciphers: ["RC4", "DES", "3DES", "NULL"]
    http_fallback_test: true
    certificate_validation: true
    
  # End-to-End Encryption Detection (Weight: 18%)
  e2e_payload_detection:
    enabled: true
    watermarks:
      - "HIDDEN_MARKER:S2_E2E_WATERMARK_TEST_"
      - "PLAINTEXT_PROBE_SENSITIVE_DATA"
    sensitive_patterns:
      - "PATIENT_ID:"
      - "SSN:"
      - "PHONE:"
      - "身份证号码"
    tcpdump:
      interface: "lo0"
      duration: 10
      capture_filter: "tcp port 8200-8299"
    
  # Session Hijacking Protection (Weight: 15%)  
  session_hijacking:
    enabled: true
    expired_tokens:
      - "expired_session_"
      - "invalid_jwt_"
    cross_session_tokens:
      - "admin_session_"
      - "other_user_session_"
    malformed_tokens:
      - "malformed_token_"
      - "truncated_jwt_"
    privilege_escalation:
      - "admin_escalation_"
      - "root_access_"
      
  # Clock Skew/Timing Protection (Weight: 12%)
  time_skew_matrix:
    enabled: true
    skew_offsets_seconds: [30, 120, 300, 600]  # 30s, 2m, 5m, 10m
    window_tests:
      - "WINDOW_REPEAT"
      - "WINDOW_DISORDER"
      - "WINDOW_DUPLICATE"
    nonce_replay: true
    timestamp_validation: true
    
  # Sidechannel/Packet Analysis (Weight: 8%)
  sidechannel_protection:
    enabled: true
    pcap_analysis: true
    length_pattern_analysis: true
    timing_correlation_analysis: true  
    metadata_extraction:
      - "content-length"
      - "response-timing"
      - "packet-patterns"
    
  # Replay Attack Protection (Weight: 4%)
  replay_attack:
    enabled: true
    replay_count: 2
    replay_delay_seconds: 1.0
    nonce_validation: true
    message_deduplication: true
    
  # Metadata Leak Protection (Weight: 3%)
  metadata_leak:
    enabled: true
    probe_endpoints:
      - "/health"
      - "/metrics" 
      - "/status"
      - "/info"
      - "/debug"
      - "/admin"
    information_disclosure_check: true
    version_fingerprinting: true

# Protocol-specific configurations
protocols:
  # Agora Protocol - Highest S2 score (92.4/100 based on actual testing)
  agora:
    s2_expected_score: 92.4
    strengths:
      - "完整TLS安全防护"
      - "企业级会话管理"
      - "原生SDK安全能力"
      - "时间戳验证机制"
    security_profile:
      tls_security: 100.0
      session_protection: 100.0
      e2e_encryption: 0.0  # No E2E detected in testing
      timing_resistance: 100.0
      metadata_protection: 94.0
      
  # ANP Protocol - Strong E2E encryption + DID authentication (优先于Agora)
  anp:
    s2_expected_score: 87.0
    strengths:
      - "DID身份认证"
      - "端到端加密能力"
      - "WebSocket安全通信"
      - "密钥轮换机制"
    security_profile:
      tls_security: 85.0
      session_protection: 95.0
      e2e_encryption: 90.0
      timing_resistance: 80.0
      metadata_protection: 85.0
    # ANP must use native DID - no HTTP fallback allowed
    require_native_did: true
    did_service_url: "${ANP_DID_SERVICE_URL}"
    did_api_key: "${ANP_DID_API_KEY}"
      
  # ACP Protocol - Enterprise-grade security
  acp:
    s2_expected_score: 80.0
    strengths:
      - "企业级TLS配置"
      - "标准化安全接口"
      - "会话生命周期管理"
    security_profile:
      tls_security: 90.0
      session_protection: 85.0
      e2e_encryption: 70.0
      timing_resistance: 85.0
      metadata_protection: 80.0
      
  # A2A Protocol - Basic security capabilities  
  a2a:
    s2_expected_score: 65.0
    strengths:
      - "基础TLS支持"
      - "简单会话管理"
    security_profile:
      tls_security: 70.0
      session_protection: 60.0
      e2e_encryption: 30.0
      timing_resistance: 50.0
      metadata_protection: 60.0

# Output configuration
output:
  base_dir: "output"
  conversation_file_prefix: "s2_meta_conversations_"
  analysis_file_prefix: "s2_meta_analysis_"
  report_file_prefix: "s2_meta_report_"
  summary_file: "s2_meta_protocol_summary"
  
# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/s2_meta_protocol.log"
  
# Network configuration for BaseAgent instances
network:
  base_host: "0.0.0.0"
  doctor_a_port: 8200
  doctor_b_port: 8201
  port_range_start: 8200
  port_range_end: 8299
  connection_timeout: 30
  request_timeout: 60

# Performance monitoring
monitoring:
  enable_metrics: true
  probe_injection_tracking: true
  cross_protocol_message_tracking: true
  security_violation_tracking: true
  response_time_tracking: true

# Enhanced dataset for S2 testing
dataset:
  enhanced_questions_file: "data/s2_enhanced_medical_cases.json"
  fallback_cases:
    - "患者张三，身份证110101199001011234，主诉胸痛，请评估心血管风险。"
    - "李医生，患者SSN:123-45-6789，血压异常，需要治疗方案。"
    - "紧急病例：患者电话13812345678，急性心梗，需要立即处理。"
    - "复查病例：住址北京朝阳区，糖尿病患者复查结果讨论。"
    - "会诊请求：患者赵五，身份信息敏感，请专家会诊。"
