# ACP Protocol Configuration for Fail-Storm Recovery Scenario
protocol: "acp"

# Scenario configuration
scenario:
  name: "fail_storm_recovery"
  protocol: "acp"
  kill_fraction: 0.3
  recovery_duration: 60  # seconds
  fault_injection_time: 60.0  # when to inject faults
  total_runtime: 120.0  # total scenario runtime
  
# Shard QA configuration
shard_qa:
  normal_phase_duration: 30  # seconds
  data_dir: "shard_qa/data/shards"
  
# Network configuration
network:
  host: "127.0.0.1"
  port_range:
    start: 9000
    end: 9100

# ACP-specific configuration
acp:
  # ACP server settings
  server:
    timeout: 30
    max_retries: 3
  
  # ACP client settings  
  client:
    timeout: 30
    base_url_template: "http://127.0.0.1:{port}"
    
  # Recovery settings
  recovery:
    reconnect_delay: 2.0  # seconds to wait before attempting reconnection
