# Agora Protocol Configuration for Fail-Storm Recovery

# Basic scenario configuration
scenario:
  name: "fail_storm_recovery_agora"
  protocol: "agora"
  agent_count: 3
  total_runtime: 60.0
  fault_injection_time: 30.0
  kill_fraction: 0.33  # Kill 33% of agents (1 out of 3)
  recovery_duration: 60
  heartbeat_interval: 5.0
  heartbeat_timeout: 15.0

# Network configuration
network:
  heartbeat_interval: 1.0
  heartbeat_timeout: 3.0
  steady_state_threshold: 5.0
  
# Agent network configuration
agents:
  base_port: 9000
  host: "127.0.0.1"
  workspace_dir: "workspaces"
  message_timeout: 10.0
  health_check_interval: 15.0

# Shard QA configuration  
shard_qa:
  normal_duration: 30.0
  groups: 2
  questions_per_group: 3
  data_file: "shard_qa/data/shards"

# LLM configuration
llm:
  type: "openai"
  model: "gpt-4o"
  openai_api_key: "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"
  openai_base_url: "https://api.openai.com/v1"
  temperature: 0.2
  top_p: 0.7
  max_tokens: 8192
  
  # Legacy compatibility fields (will be auto-mapped)
  name: "gpt-4o"

# Agora specific configuration
agora:
  # Multi-modal communication support
  communication:
    text_enabled: true
    voice_enabled: true
    video_enabled: false
    real_time_collaboration: true
    
  # Voice/Audio settings
  audio:
    sample_rate: 16000
    channels: 1
    bitrate: 64000
    voice_activation: true
    
  # Real-time features
  real_time:
    low_latency_mode: true
    adaptive_bitrate: true
    connection_timeout: 15.0
    reconnect_attempts: 3
    
  # Agora-specific networking
  networking:
    rtc_port_range: "40000-40010"
    signaling_port: 8080
    media_server_enabled: true

# Metrics and logging
metrics:
  enabled: true
  prometheus_port: 8001
  
logging:
  level: "INFO"
  output_dir: "logs/"

# Output configuration
output:
  results_dir: "results/"
  save_llm_outputs: false
  metrics_file: "failstorm_metrics.json"
  detailed_metrics_file: "detailed_failstorm_metrics.json"
