model:
  type: "openai"  # "openai" or "local"
  name: "gpt-4o"
  temperature: 0
  openai_api_key: "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"
  openai_base_url: "https://api.openai.com/v1"

# 如果使用本地模型，配置如下:
# model:
#   type: "local"
#   name: "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"
#   temperature: 0.1
#   port: 8000
