general:
  protocol: anp
  num_conversations: 5
  max_rounds: 3

# Unified LLM Core configuration
core:
  type: "local"  # "local" or "openai"
  name: "Qwen2.5-VL-72B-Instruct"  # Model name
  temperature: 0.3
  openai_api_key: "sk-lNAfLdE1AMKr6AV6a3qaNZ86BIPdEUKdyZ26VogskVpeCDjn"
  openai_base_url: "http://0.0.0.0:8000/v1"

# ANP Protocol specific configuration
anp:
  did_authentication: true
  e2e_encryption: true
  websocket_communication: true
  privacy_features:
    enable_did_verification: true
    enable_e2e_encryption: true
    enable_websocket_security: true
  agent_nodes:
    enable_simple_node: true
    auto_generate_did: true
    privacy_metadata: true

# Dataset configuration
datasets:
  enhanced_dataset: ../data/enhanced_medical_questions.json

# Agent simulation settings
simulation:
  receptionist_id: ANP_Receptionist
  doctor_id: ANP_Doctor
  privacy_mode: strict

# Privacy analysis weights
analysis:
  name_weight: 3.0
  ssn_weight: 5.0
  phone_weight: 2.0
  address_weight: 2.0
  age_weight: 1.0
  
# ANP-specific analysis features
anp_analysis:
  track_did_authentication: true
  analyze_encryption_effectiveness: true
  monitor_websocket_security: true
  measure_protocol_overhead: true

# Debug and logging
debug:
  verbose: false
  log_anp_messages: true
  log_privacy_context: true
  log_agent_interactions: true
  log_did_operations: true
