general:
  protocol: anp
  num_conversations: 5
  max_rounds: 3

# Unified LLM Core configuration
core:
  type: "openai"  # Uses OpenAI-compatible client for NVIDIA
  name: "meta/llama-3.3-70b-instruct"  # NVIDIA LLaMA model
  temperature: 0.0
  openai_api_key: "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"
  openai_base_url: "https://integrate.api.nvidia.com/v1"

# Meta Protocol Configuration
meta:
  enabled: true
  protocol_type: "anp"
  agent_pairs: 2  # receptionist + doctor

# ANP Protocol specific configuration (for underlying agents)
anp:
  did_authentication: true
  e2e_encryption: true
  websocket_communication: true
  privacy_features:
    enable_did_verification: true
    enable_e2e_encryption: true
    enable_websocket_security: true
  agent_nodes:
    enable_simple_node: true
    auto_generate_did: true
    privacy_metadata: true

# Dataset configuration
datasets:
  enhanced_dataset: ../data/enhanced_medical_questions.json

# Agent simulation settings
simulation:
  receptionist_id: ANP_Meta_Receptionist
  doctor_id: ANP_Meta_Doctor
  privacy_mode: strict

# Privacy analysis weights
analysis:
  name_weight: 3.0
  ssn_weight: 5.0
  phone_weight: 2.0
  address_weight: 2.0
  age_weight: 1.0
  
# Meta-specific analysis features
meta_analysis:
  track_did_authentication: true
  analyze_encryption_effectiveness: true
  monitor_websocket_security: true
  measure_protocol_overhead: true
  track_meta_wrapper_performance: true

# Debug and logging
debug:
  verbose: false
  log_meta_messages: true
  log_privacy_context: true
  log_agent_interactions: true
  log_did_operations: true
