general:
  protocol: agora
  num_conversations: 5
  max_rounds: 3

# Unified LLM Core configuration
core:
  type: "openai"  # "local" or "openai"
  name: "gpt-4o"  # Model name
  temperature: 0.0
  openai_api_key: "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"
  openai_base_url: null

# Meta Protocol Configuration
meta:
  enabled: true
  protocol_type: "agora"
  agent_pairs: 2  # receptionist + doctor

# Agora Protocol specific configuration (for underlying agents)
agora:
  toolformer:
    model: "gpt-4o-mini"
    temperature: 0.1
  privacy_features:
    enable_tool_filtering: true
    enable_content_sanitization: true
    enable_protocol_validation: true
  agent_features:
    enable_langchain_integration: true
    enable_structured_responses: true
    protocol_hash_validation: false

# Dataset configuration
datasets:
  enhanced_dataset: script/safety_tech/data/enhanced_medical_questions.json

# Agent simulation settings
simulation:
  receptionist_id: Agora_Meta_Receptionist
  doctor_id: Agora_Meta_Doctor
  privacy_mode: strict

# Privacy analysis weights
analysis:
  name_weight: 3.0
  ssn_weight: 5.0
  phone_weight: 2.0
  address_weight: 2.0
  age_weight: 1.0
  
# Meta-specific analysis features
meta_analysis:
  track_tool_usage: true
  analyze_protocol_compliance: true
  monitor_langchain_interactions: true
  measure_protocol_overhead: true
  track_meta_wrapper_performance: true

# Debug and logging
debug:
  verbose: false
  log_meta_messages: true
  log_privacy_context: true
  log_agent_interactions: true
  log_did_operations: true
