general:
  protocol: acp
  num_conversations: 5
  max_rounds: 3

# Unified LLM Core configuration
core:
  type: "openai"  # Uses OpenAI-compatible client for NVIDIA
  name: "meta/llama-3.3-70b-instruct"  # NVIDIA LLaMA model
  temperature: 0.0
  openai_api_key: "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"
  openai_base_url: "https://integrate.api.nvidia.com/v1"

# Meta Protocol Configuration
meta:
  enabled: true
  protocol_type: "acp"
  agent_pairs: 2  # receptionist + doctor

# ACP Protocol specific configuration (for underlying agents)
acp:
  communication:
    timeout: 30
    retry_attempts: 3
    connection_pool_size: 10
  privacy_features:
    enable_message_encryption: true
    enable_identity_verification: true
    enable_content_filtering: true
  agent_features:
    enable_structured_responses: true
    enable_context_awareness: true
    protocol_compliance_strict: true

# Dataset configuration
datasets:
  enhanced_dataset: script/safety_tech/data/enhanced_medical_questions.json

# Agent simulation settings
simulation:
  receptionist_id: ACP_Meta_Receptionist
  doctor_id: ACP_Meta_Doctor
  privacy_mode: standard

# Privacy analysis weights
analysis:
  name_weight: 3.0
  ssn_weight: 5.0
  phone_weight: 2.0
  address_weight: 2.0
  age_weight: 1.0
  
# Meta-specific analysis features
meta_analysis:
  track_protocol_overhead: true
  analyze_meta_wrapper_performance: true
  compare_with_direct_protocol: false
  measure_response_times: true

# Debug and logging
debug:
  verbose: false
  log_meta_messages: true
  log_privacy_context: true
  log_agent_interactions: true
  log_protocol_operations: true
