general:
  protocol: agora
  num_conversations: 5
  max_rounds: 3

# Unified LLM Core configuration
core:
  type: "local"  # "local" or "openai"
  name: "Qwen2.5-VL-72B-Instruct"  # Model name
  temperature: 0.3
  # openai_api_key: "sk-lNAfLdE1AMKr6AV6a3qaNZ86BIPdEUKdyZ26VogskVpeCDjn"
  # openai_base_url: "http://47.254.87.71:3000/v1"

# Agora Protocol specific configuration
agora:
  toolformer:
    model: "gpt-4o-mini"
    temperature: 0.1
  privacy_features:
    enable_tool_filtering: true
    enable_content_sanitization: true
    enable_protocol_validation: true
  agent_features:
    enable_langchain_integration: true
    enable_structured_responses: true
    protocol_hash_validation: false

# Dataset configuration
datasets:
  enhanced_dataset: script/safety_tech/data/enhanced_medical_questions.json

# Agent simulation settings
simulation:
  receptionist_id: Agora_Receptionist
  doctor_id: Agora_Doctor
  privacy_mode: strict

# Privacy analysis weights
analysis:
  name_weight: 3.0
  ssn_weight: 5.0
  phone_weight: 2.0
  address_weight: 2.0
  age_weight: 1.0
  
# Agora-specific analysis features
agora_analysis:
  track_tool_usage: true
  analyze_protocol_compliance: true
  monitor_langchain_interactions: true
  measure_protocol_overhead: true

  
# Debug and logging
debug:
  verbose: false
  log_anp_messages: true
  log_privacy_context: true
  log_agent_interactions: true
  log_did_operations: true
