# A2A protocol configuration for Gaia multi-agent framework
protocol: "a2a"
mode: "debug"

# Runtime configuration
runtime:
  task_file: "script/gaia/dataset/2023/validation/metadata.jsonl"
  output_file: "workspaces/a2a/gaia_a2a_results.json"
  timeout: 600  # seconds per task (10 minutes for complex tasks)

# Framework configuration
framework:
  name: "multi-agent protocol framework for GAIA"
  version: "1.0.0"

network:
  host: "127.0.0.1"
  port_range:
    start: 9500
    end: 10500  # Expanded port range for multiple tasks
  timeout_seconds: 60
  max_connections: 10

agents:
  default_max_tokens: 5000
  default_priority: 1
  workspace_base: "workspaces"
  max_agent_num: 10
  agent_timeout: 10000  # milliseconds
  
  complexity_thresholds:
    low: 2000
    medium: 4000
    high: 8000

performance:
  max_execution_time: 300000  # milliseconds
  target_accuracy: 0.8
  max_total_tokens: 32768

evaluation:
  truth_file: "ground_truth.json"
  metrics_file: "metrics.json"
  artifacts_file: "run_artifacts.tar.gz"
  judge_timeout: 30  # LLM judge evaluation timeout in seconds

logging:
  level: "INFO"
  format: "[%(asctime)s] %(levelname)s: %(message)s"
  agent_logs: true
  packet_logs: true

model:
  name: "gpt-4o"
  base_url: "https://api.openai.com/v1"
  api_key: "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"
  max_tokens: 4096
  temperature: 0.0
  timeout: 30
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
