# Dummy protocol configuration for Gaia multi-agent framework
protocol: "dummy"
mode: "normal"

# Runtime configuration
runtime:
  task_file: "script/gaia/dataset/2023/validation/metadata.jsonl"
  output_file: "workspaces/dummy/gaia_dummy_results.json"
  timeout: 300  # seconds per task
  max_tasks: 1  # Test single task

# Framework configuration
framework:
  name: "multi-agent protocol framework for GAIA"
  version: "1.0.0"

network:
  host: "127.0.0.1"
  timeout_seconds: 60
  max_connections: 10

model:
  name: "gpt-4o"
  base_url: "https://api.openai.com/v1"
  api_key: "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"
  max_tokens: 4096
  temperature: 0.0