# Meta Protocol Configuration for GAIA Framework
# Intelligent protocol selection and cross-protocol communication
protocol: "meta_protocol"
mode: "mm"

# Runtime configuration
runtime:
  task_file: "script/gaia/dataset/2023/validation/metadata.jsonl"
  output_file: "workspaces/meta_protocol/gaia_meta_results.json"
  timeout: 300  # seconds per task
  max_tasks: 1  # Test single task only

meta_protocol:
  # Available protocols for intelligent selection
  available_protocols:
    - "a2a"      # Agent-to-Agent Direct (fast recovery)
    - "acp"      # Agent Communication Protocol (enterprise)
    - "agora"    # Agora Protocol (balanced performance)
    - "anp"      # Agent Network Protocol (high security)
  
  # Router configuration
  router_type: "llm_based"  # "llm_based" or "load_balanced"
  router:
    llm_model: "gpt-4o"
    temperature: 0.1
    # Performance vs reliability weighting
    performance_weight: 0.4    # Favor performance
    reliability_weight: 0.6    # Favor reliability (important for GAIA tasks)
    recovery_weight: 0.8       # Heavily favor fast recovery (for fault tolerance)
  
  # Protocol selection criteria (based on fail_storm_recovery data)
  protocol_characteristics:
    a2a:
      recovery_time: 6.0        # seconds (fastest)
      success_rate: 0.596       # 59.6%
      answer_rate: 0.191        # 19.1%
      avg_response_time: 7.39   # seconds
      best_for: ["fast_recovery", "high_throughput", "large_data"]
    
    agora:
      recovery_time: 6.1        # seconds (second fastest)
      success_rate: 0.600       # 60.0%
      answer_rate: 0.200        # 20.0%
      avg_response_time: 7.10   # seconds
      best_for: ["balanced_performance", "reliability", "stability"]
    
    anp:
      recovery_time: 10.0       # seconds (slower but secure)
      success_rate: 0.610       # 61.0% (highest)
      answer_rate: 0.220        # 22.0% (highest)
      avg_response_time: 6.76   # seconds (fastest response)
      best_for: ["security", "answer_quality", "authentication"]
    
    acp:
      recovery_time: 8.0        # seconds
      success_rate: 0.590       # 59.0%
      answer_rate: 0.179        # 17.9% (lowest)
      avg_response_time: 7.83   # seconds
      best_for: ["enterprise", "formal_protocols", "compliance"]
  
  # Performance optimization settings
  performance_optimization: true
  protocol_switching_enabled: true
  adaptive_routing: true
  
  # Fault tolerance settings (important for GAIA robustness)
  fault_tolerance:
    enable_failover: true
    max_retries_per_protocol: 3
    protocol_health_check_interval: 30  # seconds
    auto_protocol_switching: true

# LLM Configuration
llm:
  model: "gpt-4o"
  temperature: 0.1
  max_tokens: 4096
  timeout: 30.0

# Network Configuration
network:
  timeout_seconds: 60
  max_retries: 3
  health_check_interval: 15
  message_timeout: 30

# Agent Configuration Template
agents:
  # This will be populated by the planner or task configuration
  default_config:
    openai_model: "gpt-4o"
    openai_temperature: 0.1
    max_tokens: 4096
    use_meta_protocol: true
    protocol_selection: "intelligent"  # "intelligent", "fixed", or "round_robin"

# Workflow Configuration
workflow:
  execution_pattern: "intelligent_routing"
  protocol_selection_strategy: "performance_based"
  enable_cross_protocol_communication: true
  
  # Message flow patterns
  message_flow_patterns:
    analysis_task:
      - {from: 0, to: [1], protocol_preference: "anp", reason: "high_accuracy_needed"}
      - {from: 1, to: [2], protocol_preference: "a2a", reason: "fast_data_transfer"}
      - {from: 2, to: "final", protocol_preference: "agora", reason: "reliable_final_result"}
    
    collaborative_task:
      - {from: 0, to: "all", protocol_preference: "agora", reason: "broadcast_reliability"}
      - {from: "all", to: 0, protocol_preference: "a2a", reason: "fast_aggregation"}

# Logging and Monitoring
logging:
  level: "INFO"
  enable_protocol_metrics: true
  enable_performance_tracking: true
  
monitoring:
  enable_real_time_metrics: true
  metrics_collection_interval: 10  # seconds
  performance_analysis: true

# GAIA Integration Settings
gaia_integration:
  enable_tool_routing: true
  cross_protocol_tool_sharing: true
  intelligent_task_distribution: true
  adaptive_load_balancing: true
