# Fail-Storm Meta-Protocol Network Configuration
# This configuration creates 2 agents per protocol for fail-storm recovery testing

# Core LLM configuration (shared by all protocols)
core:
  protocol: "meta"  # Meta-protocol network
  type: "openai"
  name: "gpt-4o"
  openai_api_key: "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"
  openai_base_url: "https://api.openai.com/v1"
  temperature: 0.0
  max_tokens: 8192
  timeout: 30.0

# Network Configuration
network:
  topology: "mesh"  # Meta-protocol mesh network
  health_check_interval: 5
  message_timeout: 30
  base_port: 9000  # Starting port for agents

# Agent Configuration
agents:
  base_port: 9000
  host: "127.0.0.1"
  workspace_dir: "workspaces"
  message_timeout: 10.0
  health_check_interval: 15.0

# Protocol-specific configurations
protocols:
  acp:
    enabled: true
    agent_count: 2  # 2 agents per protocol for fail-storm testing
  anp:
    enabled: true
    agent_count: 2
    did_service_url: "https://did-service.example.com"
    enable_encryption: true
  agora:
    enabled: true
    agent_count: 2
  a2a:
    enabled: true
    agent_count: 2

# QA Configuration (compatible with streaming_queue pattern)
qa:
  coordinator:
    count: 1
    start_port: 9900
    data_file: "data/test_questions.json"
    result_file: "data/meta_qa_results.json"
    batch_size: 10
    first_50: true
  worker:
    count: 8  # 2 agents per protocol = 8 total
    start_port: 9000
  network:
    topology: "mesh"
  health_check_interval: 5
  max_retries: 3
  batch_size: 5
  response_timeout: 60
  metrics:
    - latency
    - accuracy
    - throughput

# Shard QA Configuration for Testing
shard_qa:
  data_dir: "data/shards"
  normal_phase_duration: 30.0
  qa_cycle_timeout: 15.0

# Scenario Configuration (fail-storm specific)
scenario:
  name: "fail_storm_meta_protocol"
  protocol: "meta"
  agent_count: 8  # 2 per protocol
  total_runtime: 300.0  # 5 minutes for testing
  fault_injection_time: 120.0  # First fault at 2 minutes
  kill_fraction: 0.375  # Kill 3 out of 8 agents
  heartbeat_interval: 10.0
  heartbeat_timeout: 30.0
  enable_reconnection: true
  reconnection_delay: 10.0
  reconnection_timeout: 30.0
  # Cyclic fail storm configuration
  cyclic_faults: true
  fault_cycle_interval: 120.0  # 2 minutes
  agents_per_fault: 3
  normal_phase_duration: 120.0  # 2 minutes normal phase
  max_groups: 1000  # Test 1000 groups

# Output Configuration
output:
  results_file: "meta_failstorm_metrics.json"
  results_dir: "results"
  logs_dir: "logs"
  artifacts_dir: "artifacts"
  llm_outputs_dir: "llm_outputs"
  log_level: "info"
  colored_output: true

# Metrics Collection
metrics:
  prometheus_enabled: false
  system_monitoring: true
  collection_interval: 5.0
  retention_period: 3600
