# ACP Protocol Configuration for Fail-Storm Recovery Scenario
protocol: "acp"

# Scenario configuration
scenario:
  name: "fail_storm_recovery"
  protocol: "acp"
  agent_count: 3
  kill_fraction: 0.3
  recovery_duration: 60  # seconds
  fault_injection_time: 30.0  # when to inject faults
  total_runtime: 60.0  # total scenario runtime
  heartbeat_interval: 5.0
  heartbeat_timeout: 15.0
  
# Shard QA configuration
shard_qa:
  normal_phase_duration: 30  # seconds
  data_dir: "shard_qa/data/shards"
  
# Network configuration
network:
  host: "127.0.0.1"
  port_range:
    start: 9000
    end: 9100

# Agent network configuration
agents:
  base_port: 9000
  host: "127.0.0.1"
  workspace_dir: "workspaces"
  message_timeout: 10.0
  health_check_interval: 15.0

# LLM configuration
llm:
  type: "openai"
  model: "gpt-4o"
  openai_api_key: "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"
  openai_base_url: "https://api.openai.com/v1"
  temperature: 0.2
  top_p: 0.7
  max_tokens: 8192
  name: "gpt-4o"
  timeout: 30.0

# ACP-specific configuration
acp:
  # ACP server settings
  server:
    timeout: 30
    max_retries: 3
  
  # ACP client settings  
  client:
    timeout: 30
    base_url_template: "http://127.0.0.1:{port}"
    
  # Recovery settings
  recovery:
    reconnect_delay: 2.0  # seconds to wait before attempting reconnection
