general:
  protocol: acp
  num_conversations: 5
  max_rounds: 3

# Unified LLM Core configuration - NVIDIA LLaMA Platform
core:
  type: "openai"  # Uses OpenAI-compatible client for NVIDIA
  name: "gpt-4o"  # NVIDIA LLaMA model
  temperature: 0.3
  openai_api_key: "sk-your-openai-api-key"
  openai_base_url: "https://api.openai.com/v1"

# ACP Protocol specific configuration
acp:
  communication:
    timeout: 30
    retry_attempts: 3
    connection_pool_size: 10
  privacy_features:
    enable_message_encryption: true
    enable_identity_verification: true
    enable_content_filtering: true
  agent_features:
    enable_structured_responses: true
    enable_context_awareness: true
    protocol_compliance_strict: true

# Dataset configuration
datasets:
  enhanced_dataset: script/safety_tech/data/enhanced_medical_questions.json

# Agent simulation settings
simulation:
  receptionist_id: ACP_Receptionist
  doctor_id: ACP_Doctor
  privacy_mode: standard

# Privacy analysis weights
analysis:
  name_weight: 3.0
  ssn_weight: 5.0
  phone_weight: 2.0
  address_weight: 2.0
  age_weight: 1.0
  
# ACP-specific analysis features
acp_analysis:
  track_protocol_overhead: true
  analyze_message_structure: true
  monitor_encryption_usage: true
  measure_response_times: true

# Debug and logging
debug:
  verbose: false
  log_acp_messages: true
  log_privacy_context: true
  log_agent_interactions: true
  log_protocol_operations: true
