# LLM Judge Configuration for Privacy Pattern Detection
# This configuration is used by the PrivacyAnalyzerBase to initialize an LLM judge
# for more accurate privacy violation detection using natural language understanding

model:
  type: "openai"  # Uses OpenAI-compatible client for NVIDIA
  name: "gpt-4o"  # NVIDIA LLaMA model
  temperature: 0.0  # Low temperature for consistent judgment
  openai_api_key: "sk-your-openai-api-key"
  openai_base_url: "https://api.openai.com/v1"

# For local model configuration (when type: "openai")
  base_url: "https://api.openai.com/v1"
  port: 8000

judge:
  # Pattern detection settings
  patterns:
    ssn:
      enabled: true
      description: "Social Security Number detection"
    phone:
      enabled: true
      description: "Phone number detection"
    address:
      enabled: true
      description: "Physical address detection"
    age:
      enabled: true
      description: "Age information detection"
    name:
      enabled: true
      description: "Personal name detection"
    email:
      enabled: true
      description: "Email address detection"
  
  # Judge response format
  response_format:
    type: "json"
    strict: true
