"""
Unified Transport Envelope (UTE) definition.
This object is the canonical, protocol-agnostic message body used inside
AgentNetwork.  All adapters only need to convert between UTE <--> native.
"""

from dataclasses import dataclass, field
from typing import Dict, Any, Optional
import time
import uuid


@dataclass
class UTE:
    """Unified Transport Envelope - canonical, protocol-agnostic message structure."""
    id: str
    src: str
    dst: str
    timestamp: float
    content: Dict[str, Any] = field(default_factory=dict)
    context: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    # -------- convenience helpers --------
    @staticmethod
    def new(
        src: str,
        dst: str,
        content: Dict[str, Any],
        context: Optional[Dict[str, Any]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> "UTE":
        """Factory creating a fresh envelope with autogenerated id + timestamp."""
        return UTE(
            id=str(uuid.uuid4()),
            src=src,
            dst=dst,
            timestamp=time.time(),
            content=content or {},
            context=context or {},
            metadata=metadata or {},
        ) 