# SimpleJSON Protocol Configuration for Fail-Storm Recovery Test

# Protocol settings
protocol: "simple_json"
protocol_config:
  coordinator_id: "coordinator"
  coordinator_card:
    protocol: "simple_json"
    agent_id: "coordinator"
    capabilities: ["network_coordination", "fault_detection"]

# Test parameters
num_agents: 8
fault_injection_time: 60  # seconds
total_runtime: 120        # seconds
fault_percentage: 0.3     # 30% of agents
max_recovery_time: 60     # seconds

# Network settings
heartbeat_interval: 5.0   # seconds
heartbeat_timeout: 15.0   # seconds
debug_mode: false

# Agent settings
agent_config:
  workspace_base: "workspaces"
  port_base: 9000
  log_level: "INFO"

# Metrics collection
metrics:
  enabled: true
  output_file: "results/failstorm_metrics.json"
  detailed_logging: false 