core:
  type: "openai"
  name: "gpt-4o"
  temperature: 0.0
  base_url: "https://api.openai.com/v1"
  port: 8000
  openai_api_key: "sk-your-openai-api-key"
  openai_base_url: "https://api.openai.com/v1"

network:
  topology: "star"
  health_check_interval: 5
  message_timeout: 30

qa:
  coordinator:
    count: 1
    start_port: 9901
    data_file: "data/top1000_simplified.jsonl"
    result_file: "scenarios/streaming_queue/results/qa_results_anp.json"
    batch_size: 50
    first_50: false
  worker:
    count: 4
    start_port: 10301
  network:
    topology: "star"
  health_check_interval: 5
  max_retries: 3
  batch_size: 5
  response_timeout: 60
  metrics:
    - latency
    - accuracy
    - throughput