# A2A Protocol Configuration for MAPF
# Agent-to-Agent communication protocol

protocol: "a2a"

# Agent and Network class paths
agent_cls: "script.async_mapf.protocol_backends.a2a.agent:A2ARobot"
net_cls: "script.async_mapf.protocol_backends.a2a.network:A2ANet"

# World configuration
world:
  size: 15
  goals: [[14, 14], [0, 14], [14, 0], [0, 0], [7, 7], [7, 0]]
  obstacles:
    - [7, 8]
    - [8, 7]
    - [8, 8]
    - [6, 7]
    - [7, 6]

# Number of agents
num_agents: 6

# Starting positions
start_positions:
  - [0, 0]
  - [14, 0]
  - [0, 14]
  - [14, 14]
  - [0, 7]
  - [14, 7]

# Agent configuration
agent_kwargs:
  channel_prefix: "mapf-agent"
  timeout_ms: 2000
  client_url: "http://localhost:8000"

# Network configuration  
net_kwargs:
  tick_ms: 100  # 100ms per tick
  controller_channel: "mapf-controller"
  broadcast_channel: "mapf-broadcast"
  client_url: "http://localhost:8000"

# A2A specific configuration
a2a_config:
  server_url: "http://localhost:8000"
  retry_attempts: 3
  connection_timeout: 5.0

# Execution settings
timeout_seconds: 180 