# Distributed MAPF Configuration
# Multi-node deployment configuration

protocol: "anp"  # Use ANP for distributed deployment

# Agent and Network class paths
agent_cls: "script.async_mapf.protocol_backends.anp.agent:ANPRobot"
net_cls: "script.async_mapf.protocol_backends.anp.network:ANPNet"

# World configuration
world:
  size: 20
  goals: 
    - [19, 19]
    - [0, 19] 
    - [19, 0]
    - [0, 0]
    - [10, 10]
    - [10, 0]
    - [0, 10]
    - [19, 10]
  obstacles:
    - [10, 9]
    - [10, 11]
    - [9, 10]
    - [11, 10]
    - [5, 5]
    - [15, 15]
    - [5, 15]
    - [15, 5]

# Number of agents
num_agents: 8

# Starting positions
start_positions:
  - [0, 0]
  - [19, 0]
  - [0, 19]
  - [19, 19]
  - [0, 10]
  - [19, 10]
  - [10, 0]
  - [10, 19]

# Distributed configuration
distributed:
  # Node definitions
  nodes:
    - "coordinator-node"
    - "agent-node-1"
    - "agent-node-2"
    - "mixed-node-1"
  
  # Coordinator settings
  coordinator_address: "ws://coordinator-node:8080"
  
  # Node role assignments
  role_assignments:
    coordinator:
      coordinator: true
      agents: []
    agent:
      coordinator: false
      agents: "auto"  # Auto-assign agents
    mixed:
      coordinator: false
      agents: "auto"
  
  # Specific node assignments (override role assignments)
  node_assignments:
    "coordinator-node":
      coordinator: true
      agents: []
    "agent-node-1":
      coordinator: false
      agents: [0, 1, 2]
    "agent-node-2":  
      coordinator: false
      agents: [3, 4, 5]
    "mixed-node-1":
      coordinator: false
      agents: [6, 7]

# ANP distributed configuration
anp_config:
  node_endpoints:
    - "ws://coordinator-node:8080"
    - "ws://agent-node-1:8080"
    - "ws://agent-node-2:8080" 
    - "ws://mixed-node-1:8080"
  distributed_mode: true
  cluster_discovery: true

# Agent configuration
agent_kwargs:
  distributed_mode: true
  node_timeout: 10.0

# Network configuration
net_kwargs:
  tick_ms: 100
  distributed_mode: true
  cluster_coordination: true

# Execution settings
timeout_seconds: 300 